{
 "title": "Application Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Среднее время выполнения генерации",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(execution_time_sum{task_name=\"src.utils.generate_pdf:generate_pdf_from_data_async\"}[5m]) / rate(execution_time_count{task_name=\"src.utils.generate_pdf:generate_pdf_from_data_async\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Логи обработчика",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{container=\"docverify-worker-1\"}"
    }
   ]
  },
  {
   "title": "Логи API",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{service_name=\"docverify-gateway-1\"} |= `message` | json | line_format `{{ .timestamp }} [{{ .level }}] {{ .logger_name }}: {{ .message }}`"
    }
   ]
  },
  {
   "title": "Количество ошибок для Endpoint ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(http_errors_total[5m])) by (endpoint, method)"
    }
   ]
  },
  {
   "title": "Количество запросов Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (endpoint, method)"
    }
   ]
  },
  {
   "title": "Request Latencies by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(routes_latency_seconds_bucket[5m])) by (le, endpoint, method))"
    }
   ]
  }
 ]
}