include:
  - ./compose.logging.yaml
  - ./compose.infrastructure.yaml

services:
  gateway:
    env_file:
      - ../../conf/.env
    restart: unless-stopped
    build:
      context: ../..
      args:
        SERVICE: gateway
      dockerfile: deployments/docker/gateway.prod.Dockerfile
    command: ./scripts/startup.sh -m -l
    ports:
    # Запрещено использовать в проде
      - "8001:8001"
    depends_on:
      database:
        condition: service_healthy
      minio:
        condition: service_healthy
    labels:
      logging: "grafana"
    networks:
      - docs_network

  worker:
    env_file:
      - ../../conf/.env
    environment:
      - PYTHONPATH=/code
    restart: unless-stopped
    build:
      context: ../..
      dockerfile: deployments/docker/worker.prod.Dockerfile
    command: ./scripts/startworker.sh -m -l
    ports:
    # Только для метрик
      - "9000:9000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    labels:
      logging: "grafana"
    networks:
      - docs_network

networks:
  docs_network:
    driver: bridge
    external: True  # Нельзя использовать в проде