services:
  loki:
    image: grafana/loki:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:3110:3100
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - loki-doc-data:/loki
      - ./configs/grafana/loki-config.yaml:/etc/loki/config.yaml
    networks:
      - docs_network

  prometheus:
    image: prom/prometheus:v2.55.1
    restart: unless-stopped
    ports:
      - 127.0.0.1:9100:9090
    volumes:
      - prometheus-doc-data:/prometheus
      - ./configs/grafana/prometheus-config.yaml:/etc/prometheus/prometheus.yml
    networks:
      - docs_network


  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - 3001:3000
    volumes:
      - grafana-doc-data:/var/lib/grafana
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
      - ./configs/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - loki
    networks:
      - docs_network

  promtail:
    image: grafana/promtail:latest
    restart: unless-stopped
    volumes:
      - ../../logs:/log
      - ./configs/grafana/promtail-config.yaml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - docs_network

volumes:
  grafana-doc-data:
  loki-doc-data:
  prometheus-doc-data: