"""Docs fixes

Revision ID: f854eece9dab
Revises: 9a177f59ef99
Create Date: 2025-04-30 19:42:28.922241

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f854eece9dab"
down_revision: Union[str, None] = "9a177f59ef99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("docs", sa.Column("status", sa.String(), nullable=False))
    op.alter_column("docs", "original_document_hash", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("docs", "original_document_path", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("docs", "original_document_path", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("docs", "original_document_hash", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("docs", "status")
    # ### end Alembic commands ###
