"""Docs base init

Revision ID: 9a177f59ef99
Revises:
Create Date: 2025-04-15 01:49:33.790146

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a177f59ef99"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "docs",
        sa.Column("original_document_hash", sa.String(), nullable=False),
        sa.Column("original_document_path", sa.String(), nullable=False),
        sa.Column("signed_document_hash", sa.String(), nullable=True),
        sa.Column("signed_document_path", sa.String(), nullable=True),
        sa.Column("is_signed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_docs")),
        sa.UniqueConstraint("original_document_hash", name=op.f("uq_docs_original_document_hash")),
        sa.UniqueConstraint("signed_document_hash", name=op.f("uq_docs_signed_document_hash")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("docs")
    # ### end Alembic commands ###
