server:
  http_listen_port: 9080

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: "doc-verify"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "doc-verify"
          app: "doc-verify"
          __path__: ./log/*.log
  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: [ "logging=grafana" ]
    relabel_configs:
      - source_labels: [ "__meta_docker_container_name" ]
        regex: "/(.*)"
        target_label: "container"